# travis-ci mozilla-addon-sdk yaml
# via http://www.theautomatedtester.co.uk/blog/2012/using-travis-ci-for-building-and-testing-firefox-addons.html
language: node_js
env:
  - DISPLAY=:99.0
before_script:
  - export DISPLAY=:99.0
  - sh /usr/bin/Xvfb :0 -auth /etc/X99.cfg -screen 0 1024x768x24 -fbdir /var/lib/xvfb -extension RANDR &
  - git submodule update --init --recursive
  - cd .addon-sdk
  - . bin/activate
  - cd ../

script:
  - cfx test
